/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FullCITest;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    
  /*  @Test void someLibraryMethodReturnsFalse() {
        Library classUnderTest = new Library();
        assertFalse(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }*/
    
}
